SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
USE mini_upwork;
START TRANSACTION;
INSERT INTO users (user_id, email, full_name, password_hash, user_type) VALUES (1, 'demo1@example.test', 'Demo user 1', 'DEMO_HASH_NOT_FOR_LOGIN', 'CLIENT');
INSERT INTO users (user_id, email, full_name, password_hash, user_type) VALUES (2, 'demo2@example.test', 'Demo user 2', 'DEMO_HASH_NOT_FOR_LOGIN', 'CLIENT');
INSERT INTO users (user_id, email, full_name, password_hash, user_type) VALUES (3, 'demo3@example.test', 'Demo user 3', 'DEMO_HASH_NOT_FOR_LOGIN', 'CLIENT');
INSERT INTO users (user_id, email, full_name, password_hash, user_type) VALUES (4, 'demo4@example.test', 'Demo user 4', 'DEMO_HASH_NOT_FOR_LOGIN', 'FREELANCER');
INSERT INTO users (user_id, email, full_name, password_hash, user_type) VALUES (5, 'demo5@example.test', 'Demo user 5', 'DEMO_HASH_NOT_FOR_LOGIN', 'FREELANCER');
INSERT INTO users (user_id, email, full_name, password_hash, user_type) VALUES (6, 'demo6@example.test', 'Demo user 6', 'DEMO_HASH_NOT_FOR_LOGIN', 'FREELANCER');
INSERT INTO users (user_id, email, full_name, password_hash, user_type) VALUES (7, 'demo7@example.test', 'Demo user 7', 'DEMO_HASH_NOT_FOR_LOGIN', 'FREELANCER');
INSERT INTO users (user_id, email, full_name, password_hash, user_type) VALUES (8, 'demo8@example.test', 'Demo user 8', 'DEMO_HASH_NOT_FOR_LOGIN', 'FREELANCER');
UPDATE clients SET company_name = CONCAT('Demo studio ', client_id);
UPDATE freelancers SET professional_title = 'Database and software specialist', hourly_rate = 25 + freelancer_id;
INSERT INTO skills (skill_name) VALUES ('SQL'), ('Python'), ('Design'), ('Java'), ('Testing'), ('Analytics');
INSERT INTO job_categories (category_name) VALUES ('Software'), ('Design'), ('Data');
INSERT INTO freelancer_skills VALUES (4,1,'EXPERT'),(4,2,'ADVANCED'),(4,5,'ADVANCED'),(5,3,'EXPERT'),(5,5,'INTERMEDIATE'),(6,1,'ADVANCED'),(6,2,'ADVANCED'),(6,6,'EXPERT'),(7,4,'ADVANCED'),(8,1,'INTERMEDIATE');
INSERT INTO jobs (job_id, client_id, category_id, title, description, budget_min, budget_max, created_at, deadline) VALUES (1,1,1,'Demo job 1','Synthetic project scope',500,1000,'2026-09-01','2027-02-01');
INSERT INTO jobs (job_id, client_id, category_id, title, description, budget_min, budget_max, created_at, deadline) VALUES (2,1,2,'Demo job 2','Synthetic project scope',400,800,'2026-09-01','2027-02-01');
INSERT INTO jobs (job_id, client_id, category_id, title, description, budget_min, budget_max, created_at, deadline) VALUES (3,2,3,'Demo job 3','Synthetic project scope',750,1500,'2026-09-01','2027-02-01');
INSERT INTO jobs (job_id, client_id, category_id, title, description, budget_min, budget_max, created_at, deadline) VALUES (4,2,1,'Demo job 4','Synthetic project scope',300,600,'2026-09-01','2027-02-01');
INSERT INTO jobs (job_id, client_id, category_id, title, description, budget_min, budget_max, created_at, deadline) VALUES (5,3,1,'Demo job 5','Synthetic project scope',1000,2000,'2026-09-01','2027-02-01');
INSERT INTO jobs (job_id, client_id, category_id, title, description, budget_min, budget_max, created_at, deadline) VALUES (6,3,3,'Demo job 6','Synthetic project scope',450,900,'2026-09-01','2027-02-01');
INSERT INTO jobs (job_id, client_id, category_id, title, description, budget_min, budget_max, created_at, deadline) VALUES (7,1,2,'Demo job 7','Synthetic project scope',250,500,'2026-09-01','2027-02-01');
INSERT INTO jobs (job_id, client_id, category_id, title, description, budget_min, budget_max, created_at, deadline) VALUES (8,2,3,'Demo job 8','Synthetic project scope',600,1200,'2026-09-01','2027-02-01');
INSERT INTO proposals (proposal_id,job_id,freelancer_id,proposed_amount,cover_letter,estimated_days,submitted_at) VALUES (1,1,4,1000,'Synthetic proposal',60,'2026-10-01');
INSERT INTO proposals (proposal_id,job_id,freelancer_id,proposed_amount,cover_letter,estimated_days,submitted_at) VALUES (2,1,6,950,'Synthetic proposal',60,'2026-10-01');
INSERT INTO proposals (proposal_id,job_id,freelancer_id,proposed_amount,cover_letter,estimated_days,submitted_at) VALUES (3,2,5,800,'Synthetic proposal',60,'2026-10-01');
INSERT INTO proposals (proposal_id,job_id,freelancer_id,proposed_amount,cover_letter,estimated_days,submitted_at) VALUES (4,2,4,750,'Synthetic proposal',60,'2026-10-01');
INSERT INTO proposals (proposal_id,job_id,freelancer_id,proposed_amount,cover_letter,estimated_days,submitted_at) VALUES (5,3,6,1500,'Synthetic proposal',60,'2026-10-01');
INSERT INTO proposals (proposal_id,job_id,freelancer_id,proposed_amount,cover_letter,estimated_days,submitted_at) VALUES (6,3,8,1400,'Synthetic proposal',60,'2026-10-01');
INSERT INTO proposals (proposal_id,job_id,freelancer_id,proposed_amount,cover_letter,estimated_days,submitted_at) VALUES (7,4,7,600,'Synthetic proposal',60,'2026-10-01');
INSERT INTO proposals (proposal_id,job_id,freelancer_id,proposed_amount,cover_letter,estimated_days,submitted_at) VALUES (8,5,4,2000,'Synthetic proposal',60,'2026-10-01');
INSERT INTO proposals (proposal_id,job_id,freelancer_id,proposed_amount,cover_letter,estimated_days,submitted_at) VALUES (9,5,7,1900,'Synthetic proposal',60,'2026-10-01');
INSERT INTO proposals (proposal_id,job_id,freelancer_id,proposed_amount,cover_letter,estimated_days,submitted_at) VALUES (10,6,6,900,'Synthetic proposal',60,'2026-10-01');
INSERT INTO proposals (proposal_id,job_id,freelancer_id,proposed_amount,cover_letter,estimated_days,submitted_at) VALUES (11,8,8,1200,'Synthetic proposal',60,'2026-10-01');
UPDATE proposals SET status = 'CLIENT_ACCEPTED' WHERE proposal_id = 1;
UPDATE proposals SET status = 'CONFIRMED' WHERE proposal_id = 1;
UPDATE proposals SET status = 'CLIENT_ACCEPTED' WHERE proposal_id = 3;
UPDATE proposals SET status = 'CONFIRMED' WHERE proposal_id = 3;
UPDATE proposals SET status = 'CLIENT_ACCEPTED' WHERE proposal_id = 5;
UPDATE proposals SET status = 'CONFIRMED' WHERE proposal_id = 5;
UPDATE proposals SET status = 'CLIENT_ACCEPTED' WHERE proposal_id = 7;
UPDATE proposals SET status = 'CONFIRMED' WHERE proposal_id = 7;
UPDATE proposals SET status = 'CLIENT_ACCEPTED' WHERE proposal_id = 8;
UPDATE proposals SET status = 'CONFIRMED' WHERE proposal_id = 8;
UPDATE proposals SET status = 'CLIENT_ACCEPTED' WHERE proposal_id = 10;
INSERT INTO milestones (milestone_id,contract_id,title,amount,due_date) VALUES (1,1,'Deliverable 1',400,DATE_ADD(CURRENT_DATE, INTERVAL 20 DAY));
INSERT INTO milestones (milestone_id,contract_id,title,amount,due_date) VALUES (2,1,'Deliverable 2',600,DATE_ADD(CURRENT_DATE, INTERVAL 20 DAY));
INSERT INTO milestones (milestone_id,contract_id,title,amount,due_date) VALUES (3,2,'Deliverable 3',300,DATE_ADD(CURRENT_DATE, INTERVAL 20 DAY));
INSERT INTO milestones (milestone_id,contract_id,title,amount,due_date) VALUES (4,2,'Deliverable 4',500,DATE_ADD(CURRENT_DATE, INTERVAL 20 DAY));
INSERT INTO milestones (milestone_id,contract_id,title,amount,due_date) VALUES (5,3,'Deliverable 5',500,DATE_ADD(CURRENT_DATE, INTERVAL 20 DAY));
INSERT INTO milestones (milestone_id,contract_id,title,amount,due_date) VALUES (6,3,'Deliverable 6',1000,DATE_ADD(CURRENT_DATE, INTERVAL 20 DAY));
INSERT INTO milestones (milestone_id,contract_id,title,amount,due_date) VALUES (7,4,'Deliverable 7',200,DATE_ADD(CURRENT_DATE, INTERVAL 20 DAY));
INSERT INTO milestones (milestone_id,contract_id,title,amount,due_date) VALUES (8,4,'Deliverable 8',400,DATE_ADD(CURRENT_DATE, INTERVAL 20 DAY));
INSERT INTO milestones (milestone_id,contract_id,title,amount,due_date) VALUES (9,5,'Deliverable 9',500,DATE_ADD(CURRENT_DATE, INTERVAL 20 DAY));
INSERT INTO milestones (milestone_id,contract_id,title,amount,due_date) VALUES (10,5,'Deliverable 10',1500,DATE_ADD(CURRENT_DATE, INTERVAL 20 DAY));
UPDATE milestones SET status='IN_PROGRESS' WHERE milestone_id=1;
UPDATE milestones SET status='COMPLETED' WHERE milestone_id=1;
UPDATE milestones SET status='IN_PROGRESS' WHERE milestone_id=2;
UPDATE milestones SET status='COMPLETED' WHERE milestone_id=2;
UPDATE milestones SET status='IN_PROGRESS' WHERE milestone_id=3;
UPDATE milestones SET status='COMPLETED' WHERE milestone_id=3;
UPDATE milestones SET status='IN_PROGRESS' WHERE milestone_id=5;
UPDATE milestones SET status='COMPLETED' WHERE milestone_id=5;
UPDATE milestones SET status='IN_PROGRESS' WHERE milestone_id=7;
UPDATE milestones SET status='COMPLETED' WHERE milestone_id=7;
UPDATE milestones SET status='IN_PROGRESS' WHERE milestone_id=9;
UPDATE milestones SET status='COMPLETED' WHERE milestone_id=9;
UPDATE milestones SET status='APPROVED' WHERE milestone_id=1;
UPDATE milestones SET status='APPROVED' WHERE milestone_id=3;
UPDATE milestones SET status='APPROVED' WHERE milestone_id=5;
UPDATE milestones SET status='APPROVED' WHERE milestone_id=7;
UPDATE milestones SET status='APPROVED' WHERE milestone_id=9;
INSERT INTO payments (payment_id,milestone_id,payer_id,payee_id,amount,payment_method,payment_status) VALUES (1,1,1,4,400,'BANK_TRANSFER','FAILED');
INSERT INTO payments (payment_id,milestone_id,payer_id,payee_id,amount,payment_method,payment_status) VALUES (2,1,1,4,400,'BANK_TRANSFER','PAID');
INSERT INTO payments (payment_id,milestone_id,payer_id,payee_id,amount,payment_method,payment_status) VALUES (3,3,1,5,300,'BANK_TRANSFER','PAID');
INSERT INTO payments (payment_id,milestone_id,payer_id,payee_id,amount,payment_method,payment_status) VALUES (4,5,2,6,500,'BANK_TRANSFER','PENDING');
INSERT INTO payments (payment_id,milestone_id,payer_id,payee_id,amount,payment_method,payment_status) VALUES (5,7,2,7,200,'BANK_TRANSFER','PAID');
INSERT INTO payments (payment_id,milestone_id,payer_id,payee_id,amount,payment_method,payment_status) VALUES (6,9,3,4,500,'BANK_TRANSFER','FAILED');
COMMIT;
